sonar.projectKey=ifs24003-pabwe2026-nextjs
sonar.projectName=ifs24003-pabwe2026-nextjs

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,dist/**,.next/**,src/main.jsx,src/setupTests.js,src/test-utils.jsx,**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx